# This is a basic workflow to run selenium tests with GitHub actions

name: Selenium Tests

# Controls when the workflow will run
on:
  # Triggers the workflow every 10 minutes
  schedule:
    - cron: '*/180 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job runs the selenium tests
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Runs the selenium tests with Maven
      - name: Run selenium tests
        run:  mvn test -DxmlFile="src/test/java/org/digitalsekola/resource/testng.xml"
